#!/usr/bin/env bash
# configure nginx serveer so that/ redirect_me is redirecting me to another page
sudo apt-get update -y
sudo apt-get install nginx -y 
# Add redirect rule to Nginx config
echo "server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
# Restart Nginx to apply changes
systemctl restart nginx

